-- Viteka support portal: private multi-tenant ticketing workspace.
alter table public.profiles
  add column if not exists pharmacy_id uuid references public.pharmacies(id);

create table if not exists public.support_companies (
  id uuid primary key default uuid_generate_v4(),
  company_id uuid not null references public.companies(id),
  pharmacy_id uuid references public.pharmacies(id),
  external_freshdesk_id text,
  name text not null,
  email text,
  phone text,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.support_contacts (
  id uuid primary key default uuid_generate_v4(),
  company_id uuid not null references public.companies(id),
  support_company_id uuid references public.support_companies(id) on delete set null,
  pharmacy_id uuid references public.pharmacies(id),
  profile_id uuid references public.profiles(id),
  external_freshdesk_id text,
  name text not null,
  title text,
  email text,
  mobile_phone text,
  work_phone text,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.support_tickets (
  id uuid primary key default uuid_generate_v4(),
  public_ticket_number bigint generated by default as identity,
  company_id uuid not null references public.companies(id),
  pharmacy_id uuid references public.pharmacies(id),
  support_company_id uuid references public.support_companies(id) on delete set null,
  requester_contact_id uuid references public.support_contacts(id) on delete set null,
  requester_profile_id uuid references public.profiles(id) on delete set null,
  external_freshdesk_id text,
  subject text not null,
  description text,
  type text,
  product text,
  source text default 'portal_cliente',
  status text default 'nuevo',
  internal_status text default 'nuevo',
  client_status text default 'abierto',
  priority_client text default 'bajo',
  priority_internal text default 'bajo',
  group_name text,
  assigned_agent_id uuid references public.profiles(id) on delete set null,
  tags text[] default '{}',
  first_response_at timestamptz,
  resolved_at timestamptz,
  closed_at timestamptz,
  archived_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint support_tickets_internal_status_check check (internal_status in ('nuevo', 'abierto', 'en_progreso', 'esperando_cliente', 'esperando_proveedor', 'resuelto', 'cerrado', 'archivado')),
  constraint support_tickets_client_status_check check (client_status in ('abierto', 'en_revision', 'pendiente_respuesta', 'resuelto', 'cerrado')),
  constraint support_tickets_priority_client_check check (priority_client in ('bajo', 'medio', 'alto', 'urgente')),
  constraint support_tickets_priority_internal_check check (priority_internal in ('bajo', 'medio', 'alto', 'urgente'))
);

create table if not exists public.support_ticket_messages (
  id uuid primary key default uuid_generate_v4(),
  ticket_id uuid not null references public.support_tickets(id) on delete cascade,
  author_profile_id uuid references public.profiles(id) on delete set null,
  author_contact_id uuid references public.support_contacts(id) on delete set null,
  author_name text,
  author_type text not null,
  body text not null,
  is_private_note boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.support_ticket_attachments (
  id uuid primary key default uuid_generate_v4(),
  ticket_id uuid not null references public.support_tickets(id) on delete cascade,
  message_id uuid references public.support_ticket_messages(id) on delete cascade,
  company_id uuid not null references public.companies(id),
  pharmacy_id uuid references public.pharmacies(id),
  file_name text not null,
  file_path text not null,
  file_size bigint,
  mime_type text,
  uploaded_by_profile_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz default now()
);

create table if not exists public.support_kb_categories (
  id uuid primary key default uuid_generate_v4(),
  company_id uuid not null references public.companies(id),
  name text not null,
  description text,
  position int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.support_kb_articles (
  id uuid primary key default uuid_generate_v4(),
  company_id uuid not null references public.companies(id),
  category_id uuid references public.support_kb_categories(id) on delete set null,
  folder_name text,
  title text not null,
  slug text unique,
  body text not null,
  status text default 'draft',
  visible_to_client boolean default false,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint support_kb_articles_status_check check (status in ('draft', 'published'))
);

create table if not exists public.support_audit_logs (
  id uuid primary key default uuid_generate_v4(),
  company_id uuid not null references public.companies(id),
  entity_type text not null,
  entity_id uuid not null,
  action text not null,
  changed_by uuid references public.profiles(id) on delete set null,
  old_values jsonb,
  new_values jsonb,
  created_at timestamptz default now()
);

create index if not exists idx_support_tickets_company_updated on public.support_tickets(company_id, updated_at desc);
create index if not exists idx_support_tickets_pharmacy_updated on public.support_tickets(pharmacy_id, updated_at desc);
create index if not exists idx_support_tickets_agent_status on public.support_tickets(assigned_agent_id, internal_status);
create index if not exists idx_support_messages_ticket_created on public.support_ticket_messages(ticket_id, created_at);
create index if not exists idx_support_contacts_pharmacy on public.support_contacts(pharmacy_id);

create or replace function public.support_get_my_pharmacy_id()
returns uuid language sql stable
as $$ select pharmacy_id from public.profiles where id = auth.uid() $$;

create or replace function public.support_is_internal()
returns boolean language sql stable
as $$ select coalesce(public.get_my_role() in ('owner', 'superadmin', 'admin', 'technician', 'tecnico', 'commercial', 'comercial'), false) $$;

create or replace function public.support_can_access_ticket(ticket_uuid uuid)
returns boolean language sql stable
as $$
  select exists (
    select 1 from public.support_tickets ticket
    where ticket.id = ticket_uuid
      and ticket.company_id = public.get_my_company_id()
      and (
        public.get_my_role() in ('owner', 'superadmin', 'admin', 'commercial', 'comercial')
        or (public.get_my_role() in ('technician', 'tecnico') and ticket.assigned_agent_id = auth.uid())
        or ticket.pharmacy_id = public.support_get_my_pharmacy_id()
      )
  )
$$;

create or replace function public.support_touch_updated_at()
returns trigger language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end
$$;

drop trigger if exists support_touch_companies on public.support_companies;
create trigger support_touch_companies before update on public.support_companies for each row execute function public.support_touch_updated_at();
drop trigger if exists support_touch_contacts on public.support_contacts;
create trigger support_touch_contacts before update on public.support_contacts for each row execute function public.support_touch_updated_at();
drop trigger if exists support_touch_tickets on public.support_tickets;
create trigger support_touch_tickets before update on public.support_tickets for each row execute function public.support_touch_updated_at();
drop trigger if exists support_touch_messages on public.support_ticket_messages;
create trigger support_touch_messages before update on public.support_ticket_messages for each row execute function public.support_touch_updated_at();
drop trigger if exists support_touch_kb_categories on public.support_kb_categories;
create trigger support_touch_kb_categories before update on public.support_kb_categories for each row execute function public.support_touch_updated_at();
drop trigger if exists support_touch_kb_articles on public.support_kb_articles;
create trigger support_touch_kb_articles before update on public.support_kb_articles for each row execute function public.support_touch_updated_at();

alter table public.support_companies enable row level security;
alter table public.support_contacts enable row level security;
alter table public.support_tickets enable row level security;
alter table public.support_ticket_messages enable row level security;
alter table public.support_ticket_attachments enable row level security;
alter table public.support_kb_categories enable row level security;
alter table public.support_kb_articles enable row level security;
alter table public.support_audit_logs enable row level security;

grant select, insert, update, delete on public.support_companies, public.support_contacts, public.support_tickets, public.support_ticket_messages, public.support_ticket_attachments, public.support_kb_categories, public.support_kb_articles, public.support_audit_logs to authenticated;
grant usage, select on sequence public.support_tickets_public_ticket_number_seq to authenticated;

create policy "support_companies_select" on public.support_companies for select to authenticated using (
  company_id = public.get_my_company_id() and (public.support_is_internal() or pharmacy_id = public.support_get_my_pharmacy_id())
);
create policy "support_companies_manage" on public.support_companies for all to authenticated using (
  company_id = public.get_my_company_id() and public.support_is_internal()
) with check (company_id = public.get_my_company_id() and public.support_is_internal());

create policy "support_contacts_select" on public.support_contacts for select to authenticated using (
  company_id = public.get_my_company_id() and (public.support_is_internal() or pharmacy_id = public.support_get_my_pharmacy_id())
);
create policy "support_contacts_manage" on public.support_contacts for all to authenticated using (
  company_id = public.get_my_company_id() and public.support_is_internal()
) with check (company_id = public.get_my_company_id() and public.support_is_internal());

create policy "support_tickets_select" on public.support_tickets for select to authenticated using (
  company_id = public.get_my_company_id() and (
    public.get_my_role() in ('owner', 'superadmin', 'admin', 'commercial', 'comercial')
    or (public.get_my_role() in ('technician', 'tecnico') and assigned_agent_id = auth.uid())
    or pharmacy_id = public.support_get_my_pharmacy_id()
  )
);
create policy "support_tickets_internal_insert" on public.support_tickets for insert to authenticated with check (
  company_id = public.get_my_company_id() and public.support_is_internal()
);
create policy "support_tickets_client_insert" on public.support_tickets for insert to authenticated with check (
  company_id = public.get_my_company_id()
  and pharmacy_id = public.support_get_my_pharmacy_id()
  and requester_profile_id = auth.uid()
  and internal_status = 'nuevo'
  and client_status = 'abierto'
);
create policy "support_tickets_internal_update" on public.support_tickets for update to authenticated using (
  company_id = public.get_my_company_id() and (
    public.get_my_role() in ('owner', 'superadmin', 'admin', 'commercial', 'comercial')
    or (public.get_my_role() in ('technician', 'tecnico') and assigned_agent_id = auth.uid())
  )
) with check (company_id = public.get_my_company_id());

create policy "support_messages_select" on public.support_ticket_messages for select to authenticated using (
  public.support_can_access_ticket(ticket_id)
  and (public.support_is_internal() or is_private_note = false)
);
create policy "support_messages_internal_insert" on public.support_ticket_messages for insert to authenticated with check (
  public.support_is_internal() and public.support_can_access_ticket(ticket_id)
);
create policy "support_messages_client_insert" on public.support_ticket_messages for insert to authenticated with check (
  is_private_note = false
  and author_profile_id = auth.uid()
  and exists (
    select 1 from public.support_tickets ticket
    where ticket.id = ticket_id
      and ticket.pharmacy_id = public.support_get_my_pharmacy_id()
      and ticket.company_id = public.get_my_company_id()
  )
);

create policy "support_attachments_select" on public.support_ticket_attachments for select to authenticated using (public.support_can_access_ticket(ticket_id));
create policy "support_attachments_insert" on public.support_ticket_attachments for insert to authenticated with check (
  company_id = public.get_my_company_id() and public.support_can_access_ticket(ticket_id)
);
create policy "support_attachments_delete" on public.support_ticket_attachments for delete to authenticated using (
  company_id = public.get_my_company_id() and public.support_is_internal()
);

create policy "support_kb_categories_select" on public.support_kb_categories for select to authenticated using (company_id = public.get_my_company_id());
create policy "support_kb_categories_manage" on public.support_kb_categories for all to authenticated using (
  company_id = public.get_my_company_id() and public.support_is_internal()
) with check (company_id = public.get_my_company_id() and public.support_is_internal());
create policy "support_kb_articles_select" on public.support_kb_articles for select to authenticated using (
  company_id = public.get_my_company_id() and (public.support_is_internal() or (status = 'published' and visible_to_client))
);
create policy "support_kb_articles_manage" on public.support_kb_articles for all to authenticated using (
  company_id = public.get_my_company_id() and public.support_is_internal()
) with check (company_id = public.get_my_company_id() and public.support_is_internal());

create policy "support_audit_logs_select" on public.support_audit_logs for select to authenticated using (
  company_id = public.get_my_company_id() and public.support_is_internal()
);
create policy "support_audit_logs_insert" on public.support_audit_logs for insert to authenticated with check (
  company_id = public.get_my_company_id() and public.support_is_internal()
);

insert into storage.buckets (id, name, public)
values ('support-attachments', 'support-attachments', false)
on conflict (id) do update set public = false;

create policy "support attachment read" on storage.objects for select to authenticated using (
  bucket_id = 'support-attachments'
  and (storage.foldername(name))[1] = public.get_my_company_id()::text
  and public.support_can_access_ticket(((storage.foldername(name))[2])::uuid)
);
create policy "support attachment upload" on storage.objects for insert to authenticated with check (
  bucket_id = 'support-attachments'
  and (storage.foldername(name))[1] = public.get_my_company_id()::text
  and public.support_can_access_ticket(((storage.foldername(name))[2])::uuid)
);
create policy "support attachment update" on storage.objects for update to authenticated using (
  bucket_id = 'support-attachments'
  and (storage.foldername(name))[1] = public.get_my_company_id()::text
  and public.support_can_access_ticket(((storage.foldername(name))[2])::uuid)
) with check (
  bucket_id = 'support-attachments'
  and (storage.foldername(name))[1] = public.get_my_company_id()::text
  and public.support_can_access_ticket(((storage.foldername(name))[2])::uuid)
);
create policy "support attachment delete" on storage.objects for delete to authenticated using (
  bucket_id = 'support-attachments'
  and (storage.foldername(name))[1] = public.get_my_company_id()::text
  and public.support_can_access_ticket(((storage.foldername(name))[2])::uuid)
);
